# Project information
site_name: Citrix StoreFront 1811 Authentication SDK
site_description: Documentation and Reference Guide for the Citrix StoreFront 1811 Authentication SDK
site_title: Developer Docs
site_url: https://developer-docs.citrix.com/

# Copyright
copyright: '&copy; 1999-2020 Citrix Systems, Inc. All rights reserved. '

# Feedback

issues_uri: https://github.com/citrix/devdocs-issue-collector/issues/new
assignees_uri:
  - ajitchelat
labels_uri:
  - documentation

extra_css:
  - 'assets/stylesheets/extra.css'
  - https://use.fontawesome.com/releases/v5.12.1/css/all.css

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme
  
  # 404 page
  static_templates:
    - 404.html
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs: false
  palette:
    primary: teal
    accent: teal
  font: false
  favicon: https://docs.citrix.com/assets/images/favicon.ico
  logo: https://developer-docs.citrix.com/_static/logo.svg
  icon: fontawesome

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - icon: fontawesome/brands/github-alt
      link: https://github.com/citrix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/citrixdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.]+'

# Page tree
nav:
- StoreFront Services Authentication SDK: index.md
- StoreFront - Authentication SDK - Third Party Notices: third-party-notices.md
- Known Issues: known-issues.md
- Security Token Services API: security-token-services-api.md
- Citrix Common Forms API: common-forms-authentication-api.md
- Citrix Common Authentication Forms Language: common-authentication-forms-language.md
- CitrixAuth Authentication Scheme: citrixauth-authentication-scheme.md
- StoreFront Authentication Form Generation: storefront-authentication-form-generation.md
- StoreFront Authentication SDK JavaScript API: storefront-authentication-sdk-javascript-api.md
- Certificate Identity Declaration Sample: sample-certificate-identity-declaration.md
- Custom Federated Logon Service Sample: custom-federated-logon-service-sample.md
- Magic Word Sample: magic-word-sample.md
- Test Forms Sample: test-forms-sample.md
- U2F Sample: u2f-sample.md
- Questions?: https://discussions.citrix.com/forum/1385-citrix-developer-exchange/